# Site settings
author: Zachary Lehmann
title: ZakLearnsToCode
header-img: img/home-bg.png
email: zlehmann@gmail.com
copyright_name: Zachary Lehmann
description: > # this means to ignore newlines until "baseurl:"
  A 36 year old environmental scientist's journey into web development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Zak_Lehmann
github_username:  zlehmann

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
